// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.tb_alerta", b =>
                {
                    b.Property<int>("alt_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("alt_id"));

                    b.Property<DateTime>("alt_dataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("alt_descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("alt_status")
                        .HasColumnType("integer");

                    b.Property<string>("alt_tipoAlerta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("alt_trasacaoId")
                        .HasColumnType("integer");

                    b.HasKey("alt_id");

                    b.HasIndex("alt_trasacaoId");

                    b.ToTable("tb_alerta", (string)null);
                });

            modelBuilder.Entity("backend.Models.tb_cartao", b =>
                {
                    b.Property<int>("crt_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("crt_id"));

                    b.Property<int>("Clientecli_id")
                        .HasColumnType("integer");

                    b.Property<int>("crt_cli_id")
                        .HasColumnType("integer");

                    b.Property<int>("crt_contaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("crt_dataValidade")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("crt_limite")
                        .HasColumnType("numeric");

                    b.Property<string>("crt_numeroCartao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("crt_status")
                        .HasColumnType("boolean");

                    b.Property<int>("crt_tipoCartao")
                        .HasColumnType("integer");

                    b.HasKey("crt_id");

                    b.HasIndex("Clientecli_id");

                    b.HasIndex("crt_contaId");

                    b.ToTable("tb_cartao", (string)null);
                });

            modelBuilder.Entity("backend.Models.tb_cliente", b =>
                {
                    b.Property<int>("cli_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("cli_id"));

                    b.Property<string>("cli_bairro")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("cli_cep")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("cli_cidade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("cli_complemento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("cli_cpf")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("cli_dataNascimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("cli_estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("cli_logradouro")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("cli_numero")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("cli_rg")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("cli_telefone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("cli_usu_id")
                        .HasColumnType("integer");

                    b.HasKey("cli_id");

                    b.HasIndex("cli_cpf")
                        .IsUnique();

                    b.HasIndex("cli_usu_id");

                    b.ToTable("tb_cliente", (string)null);
                });

            modelBuilder.Entity("backend.Models.tb_conta", b =>
                {
                    b.Property<int>("cnt_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("cnt_id"));

                    b.Property<int>("cnt_cli_id")
                        .HasColumnType("integer");

                    b.Property<string>("cnt_numeroConta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("cnt_status")
                        .HasColumnType("boolean");

                    b.Property<int>("cnt_tipoConta")
                        .HasColumnType("integer");

                    b.HasKey("cnt_id");

                    b.HasIndex("cnt_cli_id");

                    b.ToTable("tb_conta", (string)null);
                });

            modelBuilder.Entity("backend.Models.tb_saldo", b =>
                {
                    b.Property<int>("sld_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("sld_id"));

                    b.Property<int>("Clientecli_id")
                        .HasColumnType("integer");

                    b.Property<int>("sld_cli_id")
                        .HasColumnType("integer");

                    b.Property<int>("sld_contaId")
                        .HasColumnType("integer");

                    b.Property<decimal>("sld_saldo")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("sld_ultimaAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("sld_id");

                    b.HasIndex("Clientecli_id");

                    b.HasIndex("sld_contaId")
                        .IsUnique();

                    b.ToTable("tb_saldo", (string)null);
                });

            modelBuilder.Entity("backend.Models.tb_transacao", b =>
                {
                    b.Property<int>("trs_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("trs_id"));

                    b.Property<int>("trs_cli_id")
                        .HasColumnType("integer");

                    b.Property<int>("trs_cnt_id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("trs_dataHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("trs_tipoTransacao")
                        .HasColumnType("integer");

                    b.Property<decimal>("trs_valor")
                        .HasColumnType("numeric");

                    b.HasKey("trs_id");

                    b.HasIndex("trs_cnt_id");

                    b.ToTable("tb_transacao", (string)null);
                });

            modelBuilder.Entity("backend.Models.tb_usuario", b =>
                {
                    b.Property<int>("usu_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("usu_id"));

                    b.Property<DateTime>("usu_dataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("usu_email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("usu_nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("usu_senhaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("usu_status")
                        .HasColumnType("boolean");

                    b.Property<int>("usu_tipo_usuario_enum")
                        .HasColumnType("integer");

                    b.HasKey("usu_id");

                    b.ToTable("tb_usuario", (string)null);
                });

            modelBuilder.Entity("tb_logs", b =>
                {
                    b.Property<int>("log_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("log_id"));

                    b.Property<string>("log_acao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("log_dataHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("log_entidade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("log_entidadeId")
                        .HasColumnType("integer");

                    b.Property<int?>("log_usuarioId")
                        .HasColumnType("integer");

                    b.HasKey("log_id");

                    b.HasIndex("log_usuarioId");

                    b.ToTable("tb_logs", (string)null);
                });

            modelBuilder.Entity("backend.Models.tb_alerta", b =>
                {
                    b.HasOne("backend.Models.tb_transacao", "transacao")
                        .WithMany("Alertas")
                        .HasForeignKey("alt_trasacaoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("transacao");
                });

            modelBuilder.Entity("backend.Models.tb_cartao", b =>
                {
                    b.HasOne("backend.Models.tb_cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("Clientecli_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.tb_conta", "Conta")
                        .WithMany("Cartoes")
                        .HasForeignKey("crt_contaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Conta");
                });

            modelBuilder.Entity("backend.Models.tb_cliente", b =>
                {
                    b.HasOne("backend.Models.tb_usuario", "Usuario")
                        .WithMany("Clientes")
                        .HasForeignKey("cli_usu_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("backend.Models.tb_conta", b =>
                {
                    b.HasOne("backend.Models.tb_cliente", "Cliente")
                        .WithMany("Contas")
                        .HasForeignKey("cnt_cli_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("backend.Models.tb_saldo", b =>
                {
                    b.HasOne("backend.Models.tb_cliente", "Cliente")
                        .WithMany("Saldos")
                        .HasForeignKey("Clientecli_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.tb_conta", "Conta")
                        .WithOne("Saldo")
                        .HasForeignKey("backend.Models.tb_saldo", "sld_contaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Conta");
                });

            modelBuilder.Entity("backend.Models.tb_transacao", b =>
                {
                    b.HasOne("backend.Models.tb_conta", "Conta")
                        .WithMany("Transacoes")
                        .HasForeignKey("trs_cnt_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conta");
                });

            modelBuilder.Entity("tb_logs", b =>
                {
                    b.HasOne("backend.Models.tb_usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("log_usuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("backend.Models.tb_cliente", b =>
                {
                    b.Navigation("Contas");

                    b.Navigation("Saldos");
                });

            modelBuilder.Entity("backend.Models.tb_conta", b =>
                {
                    b.Navigation("Cartoes");

                    b.Navigation("Saldo")
                        .IsRequired();

                    b.Navigation("Transacoes");
                });

            modelBuilder.Entity("backend.Models.tb_transacao", b =>
                {
                    b.Navigation("Alertas");
                });

            modelBuilder.Entity("backend.Models.tb_usuario", b =>
                {
                    b.Navigation("Clientes");
                });
#pragma warning restore 612, 618
        }
    }
}
